package de.lemke.sudoku.domain.model

data class SudokuStatistics(
    val gamesStarted: Int,
    val gamesCompleted: Int,
    val winRate: Int,
    val bestTimeSudoku: Sudoku?,
    val averageTime: Int,
    val winsWithoutErrors: Int,
    val mostErrors: Int,
    val averageErrors: Int,
    val winsWithoutHints: Int,
    val mostHints: Int,
    val averageHints: Int,
    val winsWithoutNotes: Int,
    val mostNotes: Int,
    val averageNotes: Int,
    val mostGamesStartedDifficulty: Difficulty?,
    val mostGamesWonDifficulty: Difficulty?,
    val mostGamesStartedSize: Int?,
    val mostGamesWonSize: Int?,
    val currentGameStreak: Int,
    val bestGameStreak: Int,
    val completedDailySudokus: Int,
    val currentDailySudokuStreak: Int,
    val bestDailySudokuStreak: Int,
    val totalSecondsPlayed: Long,
    val hintUsageRate: Float,
    val notesUsageRate: Float,
    val eraserUsageRate: Float,
    val perfectGames: Int,
)
